version: "3"

tasks:
  reset:
    cmds:
      - sudo kubeadm reset --cri-socket=unix:///var/run/crio/crio.sock --force

  init:
    cmds:
      - sudo kubeadm init --config ./cluster/config.{{ .ENV }}.yaml
    vars:
      ENV: '{{ default "prod" .ENV }}'

  config:
    cmds:
      - mkdir -p "$HOME/.kube"
      - sudo cp /etc/kubernetes/admin.conf "$HOME/.kube/config"
      - sudo chown "$(id -u):$(id -u)" "$HOME/.kube/config"

  token:
    cmds:
      - echo "sudo kubeadm reset --force && sudo {{ .TOKEN }}"
    vars:
      TOKEN:
        sh: kubeadm token create --print-join-command

  apply:
    cmds:
      - helmfile --skip-deps apply -e {{ .ENV }}
    vars:
      ENV: '{{ default "prod" .ENV }}'

  ufw:
    cmds:
      - for: [ 179, 4789, 5473, 6443, 2379, 4149, 10250, 10255, 10256, 9099, 51820, 51821 ]
        cmd: sudo ufw allow {{ .ITEM }}/tcp

  dep:
    cmds:
      - |
        cwd=$(pwd)
        for dir in $(ls -d charts/*/); do
          cd $cwd/$dir; helm dep build &
        done
        wait
        cd $cwd

  clean:
    cmds:
      - shopt -s globstar && rm -rf */**/*.tgz

  nuke:
    cmds:
      - task: reset
      - task: init
      - task: config
      - task: apply
    vars:
      ENV: '{{ default "prod" .ENV }}'
