name: typo
version: 1.0.0
config-version: 2
profile: app
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  typo:
    stages:
      +materialized: view
    inters:
      +materialized: ephemeral
    marts:
      +materialized: table
target-path: target
