global: { }

nameOverride: ""
fullnameOverride: ""

metallb:
  enabled: true
  fullnameOverride: metallb

  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - master

  ip:
    address: 192.168.1.16-192.168.1.64
